# Generated by Django 3.0.6 on 2020-06-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_roll_no', models.IntegerField()),
                ('stu_name', models.CharField(max_length=50)),
                ('stu_class', models.CharField(max_length=50)),
                ('stu_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=50)),
                ('teacher_sub', models.CharField(max_length=50)),
                ('teacher_class', models.CharField(max_length=50)),
                ('teacher_number', models.IntegerField()),
                ('teacher_dept', models.CharField(max_length=50)),
                
            ],
        ),
    ]
