# Generated by Django 3.0.6 on 2020-06-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_fname', models.CharField(max_length=50)),
                ('std_lname', models.CharField(max_length=50)),
                ('std_class', models.IntegerField()),
            ],
        ),
    ]
