# Generated by Django 3.0.6 on 2020-06-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_newstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstudent',
            name='std_father_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newstudent',
            name='std_mother_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
