# Generated by Django 3.0.6 on 2020-06-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_auto_20200609_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstudent',
            name='std_father_occupation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newstudent',
            name='std_gender',
            field=models.CharField(default='', max_length=100),
        ),
    ]
