# Generated by Django 3.0.6 on 2020-06-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_auto_20200609_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstudent',
            name='std_brother',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newstudent',
            name='std_caste',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newstudent',
            name='std_mob_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newstudent',
            name='std_mother_occupation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newstudent',
            name='std_pho_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newstudent',
            name='std_sisters',
            field=models.IntegerField(default=0),
        ),
    ]
