# Generated by Django 3.0.6 on 2020-06-09 14:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_auto_20200609_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstudent',
            name='std_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 9, 14, 46, 9, 975435, tzinfo=utc)),
        ),
    ]
