# Generated by Django 3.0.6 on 2020-06-09 14:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_newstudent_std_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstudent',
            name='std_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 9, 14, 47, 9, 503092, tzinfo=utc)),
        ),
    ]
