# Generated by Django 3.0.6 on 2020-06-09 14:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_auto_20200609_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstudent',
            name='std_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 9, 14, 48, 11, 502814, tzinfo=utc)),
        ),
    ]
