# Generated by Django 3.0.6 on 2020-06-09 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_remove_newstudent_std_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstudent',
            name='std_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
