# Generated by Django 3.0.6 on 2020-06-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_newstudent_std_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstudent',
            name='std_aadhar_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newstudent',
            name='std_annual_income',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newstudent',
            name='std_bank_account_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newstudent',
            name='std_bank_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newstudent',
            name='std_caste_certificate_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newstudent',
            name='std_ifsc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newstudent',
            name='std_ration_card',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='newstudent',
            name='std_samagra_id',
            field=models.IntegerField(default=0),
        ),
    ]
