# Generated by Django 3.0.6 on 2020-06-10 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0013_auto_20200610_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stu_10_per',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_11_per',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_8_per',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_8_school',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_9_per',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_aadhar_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_address2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_annual_income',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_bank_account_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_bank_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_brother',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_caste',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_caste_certificate_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_city',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_father_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_father_occupation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_gender',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_ifsc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_medium',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_mob_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_mother_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_mother_occupation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_pho_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_ration_card',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_samagra_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_sisters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_state',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_zip',
            field=models.CharField(default='', max_length=50),
        ),
    ]
