# Generated by Django 3.0.6 on 2020-06-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0014_auto_20200610_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='stu_number',
        ),
        migrations.AddField(
            model_name='student',
            name='stu_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_fee_submitted',
            field=models.IntegerField(default=0),
        ),

        
    ]
