# Generated by Django 3.0.6 on 2020-06-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0016_student_stu_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('OK', 'Submitted'), ('NO', 'Not_submitted')], default='Not_submitted', max_length=20),
        ),
    ]
