# Generated by Django 3.0.6 on 2020-06-11 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0019_auto_20200611_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fee_status',
            new_name='status',
        ),
    ]
