# Generated by Django 3.0.6 on 2020-06-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0021_auto_20200611_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stu_fee_remaining',
            field=models.IntegerField(default=0),
        ),
    ]
