# Generated by Django 3.0.6 on 2020-06-11 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0022_student_stu_fee_remaining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='stu_fee_remaining',
        ),
    ]
