# Generated by Django 3.0.6 on 2020-06-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0025_remove_student_remaining_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='remaining_fee',
            field=models.IntegerField(default=0),
        ),
    ]
