# Generated by Django 3.0.6 on 2020-06-11 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0026_student_remaining_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='remaining_fee',
        ),
    ]
