# Generated by Django 3.0.6 on 2020-06-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0028_student_remaining_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stu_photo',
            field=models.ImageField(default='', upload_to='schools/images'),
        ),
    ]
