# Generated by Django 3.0.6 on 2020-06-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0029_student_stu_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stu_photo',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
