# Generated by Django 3.0.6 on 2020-06-11 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0031_auto_20200611_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='remaining_salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_aadhar_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_joining_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_leaving_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_salary',
            field=models.IntegerField(default=0),
        ),
    ]
