# Generated by Django 3.0.6 on 2020-06-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0032_auto_20200611_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_photo',
            field=models.ImageField(default='', upload_to='schools/images/'),
        ),
    ]
