# Generated by Django 3.0.6 on 2020-06-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0034_teacher_teacher_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_address2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_city',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_state',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_zip',
            field=models.CharField(default='', max_length=50),
        ),
    ]
