# Generated by Django 3.0.6 on 2020-06-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0035_auto_20200612_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stu_doc1',
            field=models.ImageField(default='', upload_to='schools/images/'),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_doc2',
            field=models.ImageField(default='', upload_to='schools/images/'),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_doc3',
            field=models.ImageField(default='', upload_to='schools/images/'),
        ),
    ]
