# Generated by Django 3.0.6 on 2020-06-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0040_auto_20200617_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id2', models.IntegerField(default=0)),
                ('school_name', models.CharField(max_length=100)),
                ('school_img', models.ImageField(default='', upload_to='schools/images/')),
                ('school_mobile_no', models.IntegerField(default=0)),
                ('school_email_id', models.EmailField(max_length=200)),
                ('school_address1', models.CharField(max_length=250)),
                ('school_address2', models.CharField(max_length=250)),
                ('school_city', models.CharField(max_length=100)),
                ('school_teachers', models.ManyToManyField(to='schools.Teacher')),
            ],
            options={
                'ordering': ['school_name'],
            },
        ),
    ]
