# Generated by Django 3.0.6 on 2020-06-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0041_schools'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['teacher_school_id']},
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_school',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_school_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schools',
            name='school_teachers',
            field=models.ManyToManyField(limit_choices_to={'school_id2': 1}, related_name='_schools_school_teachers_+', to='schools.Schools'),
        ),
    ]
