# Generated by Django 3.0.6 on 2020-06-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0042_auto_20200618_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='school_teachers',
            field=models.ManyToManyField(related_name='_schools_school_teachers_+', to='schools.Schools'),
        ),
    ]
