# Generated by Django 3.0.6 on 2020-06-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0046_schools_school_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='school_teachers',
            field=models.ManyToManyField(to='schools.Teacher'),
        ),
    ]
