# Generated by Django 3.0.6 on 2020-06-18 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0047_auto_20200618_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schools',
            name='school_teachers',
        ),
        migrations.AddField(
            model_name='schools',
            name='school_teachers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.Teacher'),
        ),
    ]
