# Generated by Django 3.0.6 on 2020-06-18 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0048_auto_20200618_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schools',
            name='school_teachers',
        ),
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='schools.Schools'),
            preserve_default=False,
        ),
    ]
