# Generated by Django 3.0.6 on 2020-06-18 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0049_auto_20200618_2226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schools',
            options={'ordering': ['school_id2']},
        ),
    ]
