# Generated by Django 3.0.6 on 2020-06-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0050_auto_20200618_2353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schools',
            options={'ordering': ['school_name']},
        ),
        migrations.AddField(
            model_name='schools',
            name='school_vision',
            field=models.TextField(default='', max_length=200),
        ),
    ]
