# Generated by Django 3.0.6 on 2020-06-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0051_auto_20200619_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='school_vision',
            field=models.CharField(default='', max_length=300),
        ),
    ]
