# Generated by Django 3.0.6 on 2020-06-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0052_auto_20200619_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.IntegerField(default=0)),
                ('video_embed_link', models.CharField(default='', max_length=200)),
                ('video_class', models.IntegerField(default=0)),
            ],
        ),
    ]
