# Generated by Django 3.0.6 on 2020-06-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0053_youtubevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='video_subject',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
