# Generated by Django 3.0.6 on 2020-06-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0054_youtubevideo_video_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='video_embed_link',
            field=models.CharField(default='', max_length=50),
        ),
    ]
