# Generated by Django 3.0.6 on 2020-06-19 17:43

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0055_auto_20200619_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='video_topic',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='school',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='schools.Schools'),
            preserve_default=False,
        ),
    ]
