# Generated by Django 3.0.6 on 2020-06-20 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0056_youtubevideo_video_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='youtubevideo',
            options={'ordering': ['video_id']},
        ),
    ]
