# Generated by Django 3.0.6 on 2020-06-20 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0057_auto_20200620_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='youtubevideo',
            options={'ordering': ['video_class']},
        ),
        migrations.RenameField(
            model_name='youtubevideo',
            old_name='school',
            new_name='video_school',
        ),
    ]
