# Generated by Django 3.0.6 on 2020-06-24 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0060_teacher_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher1',
        ),
        migrations.AddField(
            model_name='student',
            name='student_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
