# Generated by Django 3.0.6 on 2020-06-24 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0061_auto_20200624_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stu_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.Schools'),
        ),
    ]
