# Generated by Django 3.0.6 on 2020-06-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0062_student_stu_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stu_school',
            new_name='student_school',
        ),
    ]
