# Generated by Django 3.0.6 on 2020-06-24 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0063_auto_20200624_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='video_school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schools.Schools'),
        ),
    ]
