# Generated by Django 3.0.6 on 2020-06-25 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0065_teacherclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherclass',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schools.Schools'),
        ),
    ]
