# Generated by Django 3.0.6 on 2020-06-25 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0066_teacherclass_school'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherClass',
            new_name='Notification',
        ),
    ]
