# Generated by Django 3.0.6 on 2020-06-26 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0067_auto_20200625_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework_topic', models.CharField(default='', max_length=100)),
                ('homework_detail', models.CharField(default='', max_length=500)),
                ('homework_class', models.IntegerField(default=0)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.Teacher')),
            ],
        ),
    ]
