# Generated by Django 3.0.6 on 2020-06-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0068_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='homework_school',
            field=models.CharField(default='', max_length=100),
        ),
    ]
