# Generated by Django 3.0.6 on 2020-06-26 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0069_homework_homework_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onlineclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_topic', models.CharField(default='', max_length=100)),
                ('class_app', models.CharField(default='', max_length=20)),
                ('class_id', models.CharField(default='', max_length=100)),
                ('class_password', models.CharField(default='', max_length=30)),
                ('class_details', models.CharField(default='', max_length=400)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.Teacher')),
            ],
        ),
    ]
