# Generated by Django 3.0.6 on 2020-07-02 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0073_auto_20200702_1325'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
