# Generated by Django 3.0.6 on 2020-07-02 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0074_delete_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_link', models.CharField(default='', max_length=150)),
                ('notes_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.Subject')),
                ('notes_teacher', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schools.Teacher')),
            ],
            options={
                'ordering': ['notes_teacher'],
            },
        ),
    ]
