# Generated by Django 3.0.6 on 2020-07-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0075_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='notes_topic',
            field=models.CharField(default='', max_length=80),
        ),
    ]
