# Generated by Django 3.0.6 on 2020-07-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0076_notes_notes_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='school_name',
            field=models.SlugField(max_length=100),
        ),
    ]
