# Generated by Django 3.0.6 on 2020-07-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0077_auto_20200703_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='school_name',
            field=models.CharField(max_length=100),
        ),
    ]
