# Generated by Django 3.0.8 on 2020-07-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0083_enroll_enroll_form_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='enroll_form_link',
            field=models.CharField(default='', max_length=300),
        ),
    ]
