# Generated by Django 3.0.8 on 2020-07-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0084_auto_20200711_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='schools',
            name='school_image_link',
            field=models.URLField(default=''),
        ),
    ]
