# Generated by Django 3.0.8 on 2020-07-14 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0085_schools_school_image_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='stu_doc1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stu_doc2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stu_doc3',
        ),
    ]
