# Generated by Django 3.0.8 on 2020-07-17 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0087_aboutusschool_achievements_facilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('review', models.CharField(default='', max_length=500)),
                ('rating', models.CharField(default='', max_length=2)),
                ('school', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schools.Schools')),
            ],
        ),
    ]
