# Generated by Django 3.0.8 on 2020-08-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0089_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img_link',
            field=models.URLField(max_length=400),
        ),
    ]
